# Generated by Django 5.2.1 on 2025-06-04 02:54

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_people', models.CharField(max_length=50, verbose_name='Кол-во человек в команде')),
                ('cnt_year', models.CharField(max_length=50, verbose_name='Кол-во лет работы в сфере')),
                ('cnt_square', models.CharField(max_length=50, verbose_name='Кол-во кв.метров чистки')),
            ],
            options={
                'verbose_name': 'О нас на главном экране',
                'verbose_name_plural': 'О нас на главном экране',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('square', models.CharField(blank=True, max_length=250, null=True, verbose_name='Квадратура')),
                ('scope', models.CharField(max_length=250, verbose_name='Сфера услуг')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение/вопрос')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_order', models.IntegerField(verbose_name='Кол-во выполненных заказов')),
            ],
            options={
                'verbose_name': 'Информация о заказе',
                'verbose_name_plural': 'Информация о заказах',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ',
                'verbose_name_plural': 'Вопросы-Ответы',
            },
        ),
        migrations.CreateModel(
            name='ScopeServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название сферы услуг')),
            ],
            options={
                'verbose_name': 'Сфера услуг',
                'verbose_name_plural': 'Сферы услуг',
            },
        ),
        migrations.CreateModel(
            name='VideoMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Заголовок к видео')),
                ('video', models.FileField(upload_to='videos')),
            ],
            options={
                'verbose_name': 'Видео на главном экране',
                'verbose_name_plural': 'Видео на главном экране',
            },
        ),
        migrations.CreateModel(
            name='PriceServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.IntegerField(verbose_name='Площадь работы')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.scopeservices', verbose_name='Сфера')),
            ],
            options={
                'verbose_name': 'Цена услуг',
                'verbose_name_plural': 'Цены услуг',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(help_text='Например, юр.лицо или физ.лицо', max_length=150, verbose_name='Сущность')),
                ('square', models.CharField(max_length=150, verbose_name='Площадь работы')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='orders', verbose_name='Фото')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.scopeservices', verbose_name='Сфера')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('time_work', models.CharField(max_length=150, verbose_name='Часы работы')),
                ('square', models.CharField(max_length=150, verbose_name='Площадь работы')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='services', verbose_name='Фото')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.scopeservices', verbose_name='Сфера')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
