# Generated by Django 5.2.1 on 2025-06-13 05:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="square",
        ),
    ]
