# Generated by Django 5.2.1 on 2025-06-16 03:45

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_feedback_scope_remove_feedback_square'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='employee', verbose_name='Фото')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник компании',
                'verbose_name_plural': 'Сотрудники компании',
            },
        ),
    ]
