# Generated by Django 5.2.1 on 2025-06-16 03:52

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='services', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фотография услуги',
                'verbose_name_plural': 'Фотографии услуг',
            },
        ),
        migrations.RemoveField(
            model_name='services',
            name='photo',
        ),
        migrations.AddField(
            model_name='services',
            name='photos',
            field=models.ManyToManyField(to='pages.servicephoto', verbose_name='Фотографии'),
        ),
    ]
