# Generated by Django 5.2.1 on 2025-06-17 02:50

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_servicephoto_remove_services_photo_services_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='logo', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Лого для блока Нас Выбирают',
                'verbose_name_plural': 'Лого для блока Нас Выбирают',
            },
        ),
    ]
